services:
  reverse-proxy:
    image: silverapache
    container_name: silverpeas-apache
    hostname: gateway.silverpeas.io
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./log:/var/log/apache2
    networks:
      silverpeas-net:
        ipv4_address: 172.18.0.80

networks:
  silverpeas-net:
    external: true



