version: "3.9"

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-icepeas
    command:
      - --copy-service
    volumes:
      - ~/Projets/docker-silverpeas/docker-silverpeas-app/silverpeas-ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ~/Projets/docker-silverpeas/docker-silverpeas-app/silverpeas-ldap/certs:/container/service/slapd/assets/certs
    environment:
      LDAP_ORGANISATION: IcePeas
      LDAP_DOMAIN: icepeas.com
      LDAP_PASSWORD: admin
      LDAP_TLS: true
      LDAP_TLS_CRT_FILENAME: icepeas.crt
      LDAP_TLS_KEY_FILENAME: icepeas.key
      LDAP_TLS_CA_CRT_FILENAME: rootCA.pem
    domainname: silverpeas.io
    hostname: icepeas
    networks:
      silverpeas-net:
        ipv4_address: 172.18.0.20

  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - 8888:80
    depends_on:
      - ldap
    networks:
      silverpeas-net:
        ipv4_address: 172.18.0.21
   
networks:
  silverpeas-net:
    external: true

